### ISSUE TITLE
Visibility control on photos

### ISSUE THREAD

**Issue by VAISHNAVREDDYDANDU** [Ankith080/Project5#44]
The "Visibility Control on Photos" feature allows users to specify who can view their uploaded photos and comments. When uploading a photo, users can choose to create a sharing list, restricting access to specific users. If no list is provided, the photo is public and visible to everyone. If the sharing list is empty, only the photo owner can view it. The system ensures that queries return only photos the user has permission to see, based on the visibility settings. This feature enhances privacy and control over photo sharing within the application.

**Comment by NavyaSree1603** [comment]
The feature is well-explained and clearly highlights the privacy controls provided to users. You might consider clarifying what happens if the owner wants to edit the sharing list after the photo is uploaded or whether there is a way to change visibility settings later. Additionally, explaining how the system handles visibility for comments on a photo (e.g., whether they inherit the photo's settings) could make the functionality even clearer

**Comment by VAISHNAVREDDYDANDU** [comment]
The explanation is clear and detailed, but adding clarification on editing the sharing list post-upload and changing visibility settings later would enhance it further. Also, specifying how visibility settings apply to comments on a photo would provide a more comprehensive understanding.

**Comment by Ankith080** [comment]
The explanation is thorough and well-structured. Great work, team! Addressing the suggested clarifications will make it even better. Let's keep this all going well
